import type { Gap } from '../../ai/adoption/gap-analyzer.js';
import { createLinearClient } from './client.js';
import type { LinearIssue } from './client.js';

const SEVERITY_TO_PRIORITY: Record<Gap['severity'], LinearIssue['priority']> = {
  critical: 1,
  major: 2,
  minor: 3,
};

export async function syncGapsToLinear(gaps: Gap[], apiKey: string, teamId: string): Promise<void> {
  if (!apiKey) throw new Error('LINEAR_API_KEY is required');
  if (!teamId) throw new Error('LINEAR_TEAM_ID is required');

  const client = createLinearClient(apiKey);
  console.log(`\n📤 Syncing ${gaps.length} gap(s) to Linear...\n`);

  for (const gap of gaps) {
    const issue: LinearIssue = {
      title: `[Adoption Gap] ${gap.description}`,
      description: [
        `**Gap ID**: ${gap.id}`,
        `**Category**: ${gap.category}`,
        `**Severity**: ${gap.severity}`,
        '',
        '## Issue',
        gap.description,
        '',
        '## Remediation',
        gap.remediation,
        '',
        '*Auto-generated by NodeJS-Starter-V1 adoption engine*',
      ].join('\n'),
      priority: SEVERITY_TO_PRIORITY[gap.severity],
      teamId,
    };

    const created = await client.createIssue(issue);
    console.log(`  ✅ ${issue.title}`);
    console.log(`     → ${created.url}`);
  }

  console.log(`\n✅ Synced ${gaps.length} issue(s) to Linear.`);
}
